spring.application.name=MappyEnglish

# PostgreSQL

spring.datasource.url=jdbc:postgresql://localhost:5432/mappy
spring.datasource.username=bsjworld
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# SpringBoot
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

## spring-boot-starter-security ?????
#spring.security.user.name=20011616
#spring.security.user.password=seungjin1031
#spring.security.user.roles=USER

# === JWT ??? ===
# (?? ???? ? ?? ?? ? ??? ???? ?????)
jwt.secret.key=${JWT_SECRET_KEY}